In [1]:
import pandas as pd
import numpy as np

In [3]:
trainData = pd.read_csv("../data/train.csv")
testData = pd.read_csv("../data/test.csv")
validationData = pd.read_csv("../data/validation.csv")

print(f"Shape of trainData is : {trainData.shape}")
print(f"Shape of testData is : {testData.shape}")
print(f"Shape of validationData is : {validationData.shape}")
trainData.head()

Shape of trainData is : (7827, 14)
Shape of testData is : (967, 14)
Shape of validationData is : (870, 14)

,Unnamed,team,opp,host,year,month,toss,day_match,bat_first,format,fow,score,rpo,result
0,4901,australia,south_africa,sri_lanka,2012,sep,1,0,0,1,5,146,7.30,1
1,1910,india,australia,india,2020,jan,0,0,1,0,6,340,6.80,1
2,5735,canada,scotland,scotland,2009,jul,1,1,0,0,4,286,5.72,1
3,2136,australia,england,australia,1987,jan,1,1,1,0,6,225,4.50,1
4,4371,new_zealand,pakistan,uae,2009,nov,0,0,0,1,5,153,7.65,0

In [4]:
import sys
import os
sys.path.insert(0, os.path.abspath('..'))  # Adjust path as needed

from utils import pre_process

# Step 2: Encode the columns["team", "opp", "host", "month"]
categorical_cols = ["team", "opp", "host", "month"]
continuous_cols = ["Unnamed", "year", "fow", "score", "rpo"]

trainDataX, trainDataY, validationDataX, validationDataY, testDataX, testDataY =  pre_process(trainData, validationData, testData, categorical_cols = categorical_cols, continuous_cols = continuous_cols)
trainDataX.head()

After pre-processing
Shape of trainDataX is : (7827, 13)
Shape of trainDataY is : (7827,)
Shape of testDataX is : (967, 13)
Shape of testDataY is : (967,)
Shape of validationDataX is : (870, 13)
Shape of validationDataY is : (870,)

,Unnamed,team,opp,host,year,month,toss,day_match,bat_first,format,fow,score,rpo
0,0.023176,0,0,0,0.527774,0,1,0,0,1,-1.226069,-1.161778,0.976509
1,-1.050706,1,1,1,1.215295,1,0,0,1,0,-0.742084,1.817869,0.696053
2,0.322613,2,2,2,0.269953,2,1,1,0,0,-1.710053,0.988483,0.090266
3,-0.969563,0,3,3,-1.620731,1,1,1,1,0,-0.742084,0.051583,-0.594049
4,-0.167114,3,4,4,0.269953,3,0,0,0,1,-1.226069,-1.054265,1.172829

In [5]:
(trainDataX == -1).any().any(), (testDataX == -1).any().any(), (validationDataX == -1).any().any()

(False, False, False)

In [6]:
trainDataX[trainDataX["team"] == 0].head()

,Unnamed,team,opp,host,year,month,toss,day_match,bat_first,format,fow,score,rpo
0,0.023176,0,0,0,0.527774,0,1,0,0,1,-1.226069,-1.161778,0.976509
3,-0.969563,0,3,3,-1.620731,1,1,1,1,0,-0.742084,0.051583,-0.594049
10,-0.874059,0,3,1,-1.448850,7,1,1,1,0,-2.194037,0.312686,-0.403338
15,-0.794712,0,0,8,0.269953,9,0,0,1,0,-0.258100,1.249586,0.280976
18,0.280965,0,7,5,0.269953,6,1,1,1,1,-0.258100,-0.808521,1.621560

In [7]:
# t20 -> format = 1
# odi -> format = 0
print("Unique counts")
for column in trainData.columns:
    print(f"{column} :: {len(trainData[column].unique())}")

Unique counts
Unnamed :: 7827
team :: 19
opp :: 19
host :: 19
year :: 53
month :: 12
toss :: 2
day_match :: 3
bat_first :: 2
format :: 2
fow :: 10
score :: 349
rpo :: 622
result :: 2

In [8]:
# just playing around with data
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

team_summary = trainData.groupby(["team","opp", "host", "toss","result"]).size().unstack(fill_value=0)
team_summary.head(2000)

result                                        0   1
team         opp          host         toss
afganistan   bangladesh   australia    0      1   0
                          bangladesh   0      8   3
                                       1      1   3
                          india        0      0   2
                                       1      0   1
                          pakistan     0      1   0
                          uae          0      1   1
                                       1      0   1
             canada       canada       1      0   2
                          netherlands  0      0   1
                          sri_lanka    0      0   1
                          uae          0      1   1
                                       1      0   1
             ireland      india        0      0   8
                                       1      2   3
                          ireland      0      1   6
                                       1      5   2
                          netherlands  0      1   0
                          uae          0      2   7
                                       1      1   1
                          zimbambave   0      0   1
             kenya        kenya        0      1   1
                          netherlands  0      0   1
                          uae          0      1   1
                                       1      0   2
             netherlands  netherlands  0      0   2
                                       1      1   0
                          scotland     0      0   1
                          uae          0      0   1
                                       1      2   1
             scotland     india        1      0   1
                          netherlands  1      1   0
                          new_zealand  1      0   1
                          scotland     0      0   1
                                       1      1   2
                          south_africa 1      0   1
                          uae          0      1   1
                                       1      0   3
                          zimbambave   0      1   0
             sri_lanka    australia    1      1   0
                          pakistan     0      1   0
                          sri_lanka    0      1   0
                                       1      1   1
             uae          bangladesh   0      1   0
                          malaysia     0      0   1
                          scotland     0      0   1
                          uae          0      1   1
                                       1      2   3
             zimbambave   bangladesh   0      0   1
                                       1      1   0
                          india        1      0   1
                          uae          0      2   6
                                       1      0   6
                          zimbambave   0      3   6
                                       1      3   7
australia    canada       india        0      0   1
             england      australia    0      9  19
                                       1      8  23
                          england      0     19  19
                                       1     15  11
                          india        1      1   2
                          south_africa 0      0   3
                          uae          1      1   1
                          west_indis   0      1   1
             india        australia    0      6  12
                                       1      7  18
                          bangladesh   1      1   0
                          england      0      2   1
                                       1      0   1
                          india        0     13  10
                                       1     14  21
                          malaysia     1      0   1
                          new_zealand  0      0   1
                                       1      0   1
                          south_africa 0      0   2
                          sri_lanka    0      1   3
                                       1      0   1
                          uae          0      1   0
                                       1      1   1
                          west_indis   0      0   1
             netherlands  south_africa 0      0   1
             new_zealand  australia    0      7  18
                                       1      7  23
                          england      1      1   2
                          india        0      1   4
                                       1      0   2
                          new_zealand  0      6  18
                                       1     14  14
                          south_africa 0      0   1
                          sri_lanka    1      0   1
                          uae          0      0   3
                          west_indis   1      0   1
             pakistan     australia    0      9  13
                                       1      4  21
                          england      0      2   3
                                       1      2   1
                          india        1      1   0
                          kenya        0      0   2
                          pakistan     0      3   5
                                       1      2   3
                          south_africa 0      1   1
                                       1      0   1
                          sri_lanka    1      2   0
                          uae          0      4  10
                                       1      3   4
                          west_indis   1      0   1
                          zimbambave   1      2   1
             south_africa australia    0      5  11
                                       1     13  10
                          england      0      1   1
                          india        1      2   0
                          new_zealand  0      0   1
                          pakistan     0      0   1
                                       1      0   1
                          south_africa 0     12  14
                                       1     15  13
                          sri_lanka    1      0   1
                          uae          1      0   1
                          west_indis   0      1   1
                                       1      0   1
                          zimbambave   0      2   1
             sri_lanka    australia    0      9  22
                                       1      9  15
                          england      0      1   1
                                       1      1   0
                          pakistan     0      1   0
                          south_africa 1      0   3
                          sri_lanka    0      8  10
                                       1      9   5
                          uae          0      0   1
                                       1      0   2
                          west_indis   0      0   1
                                       1      0   2
             usa          england      1      0   1
             west_indis   australia    0     17  21
                                       1     13  17
                          bangladesh   1      1   0
                          england      1      4   1
                          india        0      1   1
                                       1      1   2
                          malaysia     1      1   1
                          south_africa 0      0   1
                          sri_lanka    0      1   1
                          uae          1      0   1
                          west_indis   0      8  13
                                       1     14  14
             zimbambave   australia    0      1   1
                                       1      0   4
                          england      0      0   1
                                       1      1   1
                          india        0      0   3
                                       1      0   2
                          south_africa 1      1   0
                          zimbambave   0      0   6
                                       1      1   3
bangladesh   afganistan   bangladesh   0      1   2
                                       1      3   7
                          india        1      2   0
                          pakistan     1      0   1
                          uae          0      1   0
                                       1      1   1
             bermuda      west_indis   0      0   1
                                       1      0   1
             canada       south_africa 0      1   0
                          west_indis   0      0   1
             india        australia    0      1   0
                                       1      1   0
                          bangladesh   0      7   0
                                       1      9   3
                          england      0      2   0
                          pakistan     1      1   0
                          sri_lanka    0      3   0
                                       1      2   0
                          uae          0      1   0
                                       1      1   0
                          west_indis   0      0   1
             ireland      bangladesh   0      0   5
                                       1      1   2
                          england      0      0   1
                                       1      0   1
                          ireland      0      1   3
                                       1      0   2
                          west_indis   0      1   0
             kenya        bangladesh   0      1   1
                                       1      0   1
                          india        0      1   1
                          kenya        0      0   1
                                       1      2   3
             netherlands  australia    0      0   1
                          bangladesh   0      0   1
                          india        0      0   1
                          netherlands  0      0   1
                                       1      1   0
             pakistan     australia    1      1   0
                          bangladesh   0      8   3
                                       1      9   1
                          england      0      1   1
                          kenya        1      1   0
                          new_zealand  1      2   0
                          pakistan     0      2   0
                                       1      5   0
                          south_africa 0      1   0
                          sri_lanka    0      4   0
                                       1      2   0
                          uae          1      1   0
             scotland     bangladesh   0      0   1
                                       1      0   1
                          netherlands  0      1   0
                          new_zealand  1      0   1
             sri_lanka    australia    0      1   0
                          bangladesh   0      7   0
                                       1      7   6
                          india        0      1   0
                          pakistan     0      1   0
                                       1      1   0
                          south_africa 0      1   0
                          sri_lanka    0      4   1
                                       1     14   2
                          uae          0      2   0
                                       1      1   1
                          west_indis   1      1   0
             uae          bangladesh   0      0   1
                          uae          0      0   2
             zimbambave   australia    1      0   1
                          bangladesh   0      5  14
                                       1      5  16
                          india        0      0   1
                          kenya        0      1   0
                          zimbambave   0     11  13
                                       1      4   4
bermuda      bangladesh   west_indis   0      1   0
                                       1      1   0
             canada       bermuda      0      0   1
                                       1      1   0
                          canada       0      0   1
                                       1      2   1
                          ireland      0      1   0
                          kenya        1      1   0
                          south_africa 0      2   0
                          west_indis   1      1   1
             india        west_indis   1      1   0
             ireland      ireland      0      1   0
                          kenya        0      1   0
             kenya        kenya        0      4   0
                                       1      1   0
                          south_africa 0      1   0
                          uae          0      1   0
             netherlands  netherlands  0      1   0
                                       1      1   0
                          south_africa 0      0   1
                                       1      1   0
                          uae          0      1   0
             scotland     ireland      0      1   0
                          uae          1      1   0
             sri_lanka    west_indis   0      1   0
             usa          bermuda      1      0   2
                          west_indis   0      1   0
             zimbambave   west_indis   0      1   0
                                       1      1   0
canada       afganistan   canada       0      2   0
                          sri_lanka    1      1   0
                          uae          0      1   0
                                       1      1   1
             australia    england      0      1   0
             bangladesh   south_africa 1      0   1
                          west_indis   1      1   0
             bermuda      bermuda      0      0   1
                                       1      1   0
                          canada       0      1   2
                                       1      2   0
                          ireland      1      0   1
                          kenya        0      0   1
                          south_africa 1      0   1
                          west_indis   0      1   2
             ireland      canada       0      0   1
                                       1      1   0
                          ireland      0      1   0
                                       1      1   0
                          kenya        1      0   1
                          netherlands  1      1   0
                          south_africa 0      1   0
                          sri_lanka    0      0   1
                          uae          1      1   1
             kenya        canada       0      1   0
                                       1      0   1
                          ireland      1      1   0
                          kenya        0      2   0
                                       1      1   0
                          south_africa 1      1   0
                          uae          0      2   1
                                       1      2   0
                          west_indis   0      1   0
             netherlands  canada       0      2   0
                          kenya        1      1   0
                          netherlands  1      2   0
                          new_zealand  1      1   0
                          south_africa 0      1   0
                                       1      1   0
                          uae          0      1   0
                                       1      1   0
             new_zealand  south_africa 0      1   0
                          west_indis   1      1   0
             pakistan     canada       0      1   0
                          england      1      1   0
                          sri_lanka    0      1   0
             scotland     kenya        1      3   0
                          netherlands  0      1   0
                          new_zealand  1      1   0
                          scotland     1      1   1
                          south_africa 0      0   1
             sri_lanka    canada       0      1   0
                          sri_lanka    0      1   0
             uae          uae          1      1   0
             usa          bermuda      0      0   2
             west_indis   canada       0      1   0
                          south_africa 0      1   0
                          west_indis   0      1   0
             zimbambave   canada       1      1   0
                          india        0      1   0
                          west_indis   0      1   0
england      australia    australia    0     27  10
                                       1     21  13
                          england      0      8  17
                                       1     21  10
                          india        0      2   1
                          south_africa 1      3   0
                          uae          0      1   1
                                       1      0   1
                          west_indis   1      1   1
             india        australia    1      1   1
                          england      0     12  12
                                       1      8  13
                          india        0     13   8
                                       1     15  11
                          south_africa 0      1   0
                          sri_lanka    1      1   0
                          uae          0      1   1
             netherlands  bangladesh   1      1   0
                          netherlands  0      0   2
                                       1      0   1
                          pakistan     1      0   1
                          south_africa 1      0   1
             new_zealand  australia    0      4   5
                                       1      3   2
                          bangladesh   0      1   0
                          england      0     10  11
                                       1      4   9
                          india        1      0   1
                          new_zealand  0      6  13
                                       1     13  10
                          south_africa 0      1   0
                                       1      1   0
                          uae          0      1   0
                          west_indis   0      1   1
             pakistan     australia    0      2   1
                                       1      0   1
                          england      0      7  22
                                       1      6  14
                          india        0      1   0
                          pakistan     0      5   3
                                       1      7   8
                          south_africa 1      0   1
                          uae          0      1   4
                                       1      1  10
                          west_indis   1      0   1
             south_africa bangladesh   1      2   0
                          england      0      4  11
                                       1      7   5
                          india        1      0   1
                          kenya        1      1   0
                          pakistan     0      1   0
                          south_africa 0     14   5
                                       1      3   6
                          uae          1      1   0
                          west_indis   1      1   1
             sri_lanka    australia    0      2   4
                                       1      1   3
                          bangladesh   1      0   1
                          england      0      4   9
                                       1      9  12
                          india        0      0   1
                                       1      0   1

In [9]:
# Question A

# now build a decision tree to predict the result given the trainingData
# Step 0: 
from decisionTree import DecisionTreeModel
from utils import evaluate, plotA

maxDepths = [5, 10, 15, 20]
trainAccuracies = []
validationAccuracies = []
testAccuracies = []

categorical_cols = ["team", "opp", "host", "month", "toss", "day_match", "bat_first", "format"]
continuous_cols = ["Unnamed", "year", "fow", "score", "rpo"]

for maxDepth in maxDepths:
    print(f"---------------Testing for maxDepth : {maxDepth}-------------------")
    model = DecisionTreeModel(maxDepth, categorical_cols = categorical_cols, continuous_cols = continuous_cols)

    # TRAIN THE MODEL WITH TRAIN DATA
    print("Training on the train data")
    model.fit(trainDataX, trainDataY)

    # if maxDepth == 5:
    #     model.print_tree()
    
    # PREDICT THE MODEL ON TRAIN DATA
    print("Prediction on train data")
    predictY_train = model.predict(trainDataX)
    
    # EVALUATION
    train_accuracy = evaluate(predictY_train, trainDataY)
    
    # PREDICT THE MODEL ON VALIDATION DATA
    print("Prediction on validation data")
    predictY_validation = model.predict(validationDataX)
    
    # EVALUATION
    validation_accuracy = evaluate(predictY_validation, validationDataY)
    
    # PREDICT THE MODEL ON Test DATA
    print("Prediction on test data")
    predictY_test = model.predict(testDataX)
    
    # EVALUATION
    test_accuracy = evaluate(predictY_test, testDataY)

    trainAccuracies.append(train_accuracy)
    validationAccuracies.append(validation_accuracy)
    testAccuracies.append(test_accuracy)

plotA(maxDepths, trainAccuracies, validationAccuracies, testAccuracies)

---------------Testing for maxDepth : 5-------------------
Training on the train data
Prediction on train data
Accuracy : 0.889, Precision: 0.910, Recall: 0.866, F1-Score: 0.888
Prediction on validation data
Accuracy : 0.583, Precision: 0.587, Recall: 0.553, F1-Score: 0.569
Prediction on test data
Accuracy : 0.582, Precision: 0.557, Recall: 0.572, F1-Score: 0.565
---------------Testing for maxDepth : 10-------------------
Training on the train data
Prediction on train data
Accuracy : 0.995, Precision: 0.999, Recall: 0.991, F1-Score: 0.995
Prediction on validation data
Accuracy : 0.606, Precision: 0.605, Recall: 0.606, F1-Score: 0.605
Prediction on test data
Accuracy : 0.589, Precision: 0.563, Recall: 0.598, F1-Score: 0.580
---------------Testing for maxDepth : 15-------------------
Training on the train data
Prediction on train data
Accuracy : 0.996, Precision: 0.999, Recall: 0.992, F1-Score: 0.996
Prediction on validation data
Accuracy : 0.606, Precision: 0.605, Recall: 0.606, F1-Score: 0.605
Prediction on test data
Accuracy : 0.589, Precision: 0.563, Recall: 0.598, F1-Score: 0.580
---------------Testing for maxDepth : 20-------------------
Training on the train data
Prediction on train data
Accuracy : 0.996, Precision: 0.999, Recall: 0.992, F1-Score: 0.996
Prediction on validation data
Accuracy : 0.606, Precision: 0.605, Recall: 0.606, F1-Score: 0.605
Prediction on test data
Accuracy : 0.589, Precision: 0.563, Recall: 0.598, F1-Score: 0.580

TypeError: plotA() missing 1 required positional argument: 'file_path'

| Max Depth | Train Accuracy | Validation Accuracy | Test Accuracy |
| :-------- | :------------- | :------------------ | :------------ |
| 5         | 0.889          | 0.585               | 0.583         |
| 10        | 0.995          | 0.608               | 0.592         |
| 15        | 0.996          | 0.608               | 0.592         |
| 20        | 0.996          | 0.608               | 0.592         |

When depth = 5,
The model underfits slightly — not enough complexity to capture all training patterns.
Training accuracy (0.889) < 1.0 indicates this.

As depth increases to 10 and beyond,

The tree almost perfectly memorizes training data (train accuracy → 0.995+).
However, test accuracy barely improves (~0.59) — showing overfitting.

After depth = 10, there’s no meaningful performance gain on test/validation.

General observation:
Increasing tree depth makes the model more expressive but reduces generalization.

Optimal depth seems to be around 10 for this dataset.

As the maximum depth of the decision tree increases, the model achieves nearly perfect accuracy on the training set, indicating overfitting. However, the validation and test accuracies remain almost constant around 0.592, suggesting that the model fails to generalize beyond a certain complexity level. The optimal depth appears to be around 10, beyond which deeper trees add no value to predictive performance.